kk

In [2]:
!pip install torch

  Using cached torch-2.7.1-cp313-none-macosx_11_0_arm64.whl.metadata (29 kB)
  Using cached filelock-3.18.0-py3-none-any.whl.metadata (2.9 kB)
  Using cached setuptools-80.9.0-py3-none-any.whl.metadata (6.6 kB)
  Using cached sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
  Using cached networkx-3.5-py3-none-any.whl.metadata (6.3 kB)
  Using cached jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
  Using cached fsspec-2025.7.0-py3-none-any.whl.metadata (12 kB)
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
  Using cached MarkupSafe-3.0.2-cp313-cp313-macosx_11_0_arm64.whl.metadata (4.0 kB)
Using cached torch-2.7.1-cp313-none-macosx_11_0_arm64.whl (68.6 MB)
Using cached sympy-1.14.0-py3-none-any.whl (6.3 MB)
Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Using cached filelock-3.18.0-py3-none-any.whl (16 kB)
Using cached fsspec-2025.7.0-py3-none-any.whl (199 kB)
Using cached jinja2-3.1.6-py3-none-any.whl (134 kB)
Using cached MarkupSafe-3.0.2-cp313-cp313-macosx_11_0_ar

In [3]:
import torch

# Check if GPU is available and set device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# Create tensor A: 3x2 matrix with random values from normal distribution
A = torch.randn(3, 2)
print(f"A:\n{A}\n")

# Create tensor B: 2x3 matrix with random values from normal distribution
B = torch.randn(2, 3)
print(f"B:\n{B}\n")

# Compute matrix multiplication: C = A @ B
# @ is the matrix multiplication operator; result is 3x3
C = A @ B
print(f"C (A @ B):\n{C}\n")

# Compute element-wise addition: D = A + ones_like(A)
# ones_like creates a tensor of ones matching A's shape
D = A + torch.ones_like(A)
print(f"D (A + ones):\n{D}\n")

# Move tensor C to GPU if available, else keep on CPU
C = C.to(device)
print(f"C is on device: {C.device}\n")

# Move tensor D to GPU if available, else keep on CPU
D = D.to(device)
print(f"D is on device: {D.device}")

Using device: cpu
A:
tensor([[0.5773, 1.3215],
        [0.6862, 0.9049],
        [0.3667, 0.5851]])

B:
tensor([[-0.3229,  0.3479,  0.5602],
        [-0.3126, -0.3931, -1.3776]])

C (A @ B):
tensor([[-0.5996, -0.3186, -1.4971],
        [-0.5045, -0.1170, -0.8622],
        [-0.3013, -0.1024, -0.6005]])

D (A + ones):
tensor([[1.5773, 2.3215],
        [1.6862, 1.9049],
        [1.3667, 1.5851]])

C is on device: cpu

D is on device: cpu
