In [1]:
!pip install torch

In [2]:
import torch

# Check if GPU is available and set device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# Create tensor A: 3x2 matrix with random values from normal distribution
A = torch.randn(3, 2)
print(f"A:\n{A}\n")

# Create tensor B: 2x3 matrix with random values from normal distribution
B = torch.randn(2, 3)
print(f"B:\n{B}\n")

# Compute matrix multiplication: C = A @ B
# @ is the matrix multiplication operator; result is 3x3
C = A @ B
print(f"C (A @ B):\n{C}\n")

# Compute element-wise addition: D = A + ones_like(A)
# ones_like creates a tensor of ones matching A's shape
D = A + torch.ones_like(A)
print(f"D (A + ones):\n{D}\n")

# Move tensor C to GPU if available, else keep on CPU
C = C.to(device)
print(f"C is on device: {C.device}\n")

# Move tensor D to GPU if available, else keep on CPU
D = D.to(device)
print(f"D is on device: {D.device}")

Using device: cpu
A:
tensor([[ 0.7071, -0.1511],
        [ 1.1139, -0.2966],
        [ 0.2214, -0.7422]])

B:
tensor([[-0.6916, -1.0654, -2.6135],
        [-1.7431, -0.2545, -0.5129]])

C (A @ B):
tensor([[-0.2256, -0.7148, -1.7704],
        [-0.2534, -1.1112, -2.7590],
        [ 1.1405, -0.0470, -0.1980]])

D (A + ones):
tensor([[1.7071, 0.8489],
        [2.1139, 0.7034],
        [1.2214, 0.2578]])

C is on device: cpu

D is on device: cpu
